version: "3.6"
services:
  frontend-hack:
    container_name: frontend-hack
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
      target: development
    ports:
      - "8000:8080"
    volumes:
      - ./frontend/src:/opt/app/src
      - ./frontend/public:/opt/app/public
  # maria-db-hack:
  #   image: mariadb:10.4.18
  #   restart: always
  #   container_name: maria-db-hack
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: db
  #   ports:
  #     - "7200:3306"

  # phpmyadmin-hack:
  #   container_name: phpmyadmin-hack
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8100:80"
  #   volumes:
  #     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  # mongo-db-hack:
  #   image: mongo
  #   restart: always
  #   container_name: mongo-db-hack
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - "7300:27017"
  #   command: mongod --quiet --logpath /dev/null
