name: Docker

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      VUE_APP_API_URL: https://start-hack-2022-backend-xertbtzkda-uc.a.run.app
      VUE_APP_WEBSOCKET_URL: wss://start-hack-2022-backend-xertbtzkda-uc.a.run.app
      BACKEND_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}_backend
      FRONTEND_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}_frontend
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17

      - name: Install Node.js dependencies
        working-directory: ./frontend
        run: yarn

      - name: Build Node.js dependencies
        working-directory: ./frontend
        run: yarn build

      - name: Build Docker image backend
        run: docker build ./backend -t $BACKEND_IMAGE_NAME

      - name: Build Docker image frontend
        run: docker build --target staging ./frontend -t $FRONTEND_IMAGE_NAME

      - name: Push Docker image backend
        run: docker push $BACKEND_IMAGE_NAME

      - name: Push Docker image frontend
        run: docker push $FRONTEND_IMAGE_NAME

      - name: Deploy Docker image backend
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }}-backend --image $BACKEND_IMAGE_NAME --region us-central1 --platform managed

      - name: Deploy Docker image frontend
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }}-frontend --image $FRONTEND_IMAGE_NAME --region us-central1 --platform managed
